"""init models

Revision ID: 6426c3ea1eb8
Revises: 
Create Date: 2025-11-05 23:28:43.703615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6426c3ea1eb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index('ix_images_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('personas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('persona_json', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('openai_job_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personas_openai_job_id'), ['openai_job_id'], unique=False)
        batch_op.create_index('ix_personas_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.create_index('ix_scripts_persona_created', ['persona_id', 'created_at'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('script_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index('ix_videos_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index('ix_videos_status_created')

    op.drop_table('videos')
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_index('ix_scripts_persona_created')

    op.drop_table('scripts')
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_index('ix_personas_user_created')
        batch_op.drop_index(batch_op.f('ix_personas_openai_job_id'))

    op.drop_table('personas')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index('ix_images_user_created')

    op.drop_table('images')
    op.drop_table('users')
    # ### end Alembic commands ###
